# =============================================================================
# rag_engine.py
#
# Purpose:
#   This module implements the core Retrieval-Augmented Generation (RAG) pipeline for the RCA assistant.
#   It retrieves the most relevant log messages for a user query, constructs a prompt for the LLM,
#   and returns a concise root cause analysis generated by the language model.
# =============================================================================

from src.retriever import get_top_k_logs
from src.mock_bedrock import query_llm

def generate_prompt(query: str, retrieved_logs: list) -> str:
    # Constructs a prompt for the LLM using the user query and the retrieved log messages with context.
    logs_formatted = []
    for _, row in retrieved_logs:
        log_entry = f"- Protocol: {row.get('error_type', 'N/A')}, Info: {row.get('cleaned_message', 'N/A')}"
        if 'Source' in row and 'Destination' in row:
            log_entry = f"- Source: {row['Source']}, Destination: {row['Destination']}, Protocol: {row.get('error_type', 'N/A')}, Info: {row.get('cleaned_message', 'N/A')}"
        logs_formatted.append(log_entry)
    
    logs_text = "\n".join(logs_formatted)
    
    return (
        f"You are a 5G Core Network Engineer. Analyze these Open5GS signaling logs (Source, Destination, Protocol, Info) "
        f"to find the root cause of the connection failure.\n\n"
        f"User Query:\n{query}\n\nRelevant Logs:\n{logs_text}"
    )

def rca_pipeline(query: str, k: int = 3, model: str = "openrouter/auto") -> dict:
    # Main RAG pipeline:
    # 1. Retrieve the top-k most relevant logs for the query.
    # 2. Generate a prompt combining the query and logs.
    # 3. Query the LLM with the prompt and return the response and retrieved logs.
    retrieved_logs = get_top_k_logs(query, k=k)
    prompt = generate_prompt(query, retrieved_logs)
    response = query_llm(prompt, model=model)
    return {
        "answer": response,
        "retrieved_logs": retrieved_logs
    }